name: hugo

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes and all extra projects
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
              
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true

      - name: Setup nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: 12               

      - name: Build        
        run: | 
         npm install -g postcss-cli
         npm install autoprefixer
         npm audit fix
         hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{secrets.personal_token}}
          external_repository: British-Oceanographic-Data-Centre/COAsT
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
