name: notebook_to_md (tidegauge)

on:
  # External webhook trigger
  repository_dispatch:
   types: [push-notebook]

jobs:
  commit-notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout site
        uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes and all extra projects
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: site

      - name: Checkout coast
        uses: actions/checkout@v3
        with:
          repository: British-Oceanographic-Data-Centre/COAsT
          ref: develop
          path: external

      - name: Prepare environement
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: coast
          environment-file: external/environment.yml
          python-version: 3.8.10
      - name: prep exec notebooks
        run: |
          conda info
          conda list
          conda config --show
          cd $GITHUB_WORKSPACE/external
          sudo apt install wget unzip -y
          wget -q https://linkedsystems.uk/erddap/files/COAsT_example_files/COAsT_example_files.zip
          unzip COAsT_example_files.zip && mv COAsT_example_files ./example_scripts/notebook_tutorials/runnable_notebooks/tidegauge/example_files
          ls /home/runner/work/COAsT-site/COAsT-site/external/example_scripts/notebook_tutorials/runnable_notebooks/tidegauge/example_files
          mkdir -p ./example_scripts/notebook_tutorials/markdown/tidegauge
          ls ./example_scripts/notebooks
          pip install .
          mv config ./example_scripts/notebook_tutorials/runnable_notebooks/tidegauge/config
          bash notebook_to_md.sh tidegauge
      - name: convert notebooks
        run: |
          cd $GITHUB_WORKSPACE/external/example_scripts/notebook_tutorials/
          ls ./markdown
          pwd    
          ls ./markdown/tidegauge    
          echo "Move tidegauge markdown examples"
          mv ./markdown/tidegauge/tidetable_tutorial.md $GITHUB_WORKSPACE/site/content/en/docs/Examples/Notebooks/Tidegauge/
          mv ./markdown/tidegauge/tidegauge_validation_tutorial.md $GITHUB_WORKSPACE/site/content/en/docs/Examples/Notebooks/Tidegauge/
          echo "Move images"
          rsync -r ./markdown_images/tidegauge/ $GITHUB_WORKSPACE/site/static

      - name: commit changes
        run: |
          cd $GITHUB_WORKSPACE/site
          git config --global user.name "MarkDownBot"
          git config --global author.name "MarkDownBot"
          git config --global user.email "bodcsoft@bodc.ac.uk"
          git config --global author.email "bodcsoft@bodc.ac.uk"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout develop
          git pull        
          git add content/en/docs/Examples/Notebooks/Tidegauge/*
          git add static/*
          git commit -am "Updated Altimetry notebook pages from coast repo."
          git push origin develop
