name: notebook_to_md

on:
  # External webhook trigger
  repository_dispatch:
    types: [push]

jobs:
  commit-notebooks:
    if: ${{ github.event.client_payload.branch == develop }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout site
        uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes and all extra projects
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          path: site

      - name: Checkout coast
        uses: actions/checkout@v3
        with:
          repository: British-Oceanographic-Data-Centre/COAsT
          ref: develop
          path: external

      - name: add python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: covert notebooks
        run: |
          cd $GITHUB_WORKSPACE/external
          bash notebook_to_md.sh
          mv $GITHUB_WORKSPACE/external/example_scripts/notebooks/markdown/* $GITHUB_WORKSPACE/site/content/en/docs/Examples/Notebooks/

      - name: commit changes
        run: |
          cd $GITHUB_WORKSPACE/site
          git config --global user.name "MarkDownBot"
          git config --global author.name "MarkDownBot"
          git config --global user.email "bodcsoft@bodc.ac.uk"
          git config --global author.email "bodcsoft@bodc.ac.uk"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git add content/en/docs/Examples/Notebooks/*
          git commit -am "Updated notebook pages from coast repo."
          git push origin $GITHUB_HEAD_REF
          
